services:
  catalogdb:
    container_name: catalogdb
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalogdb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  catalog.api:
    container_name: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__CatalogDb: "Host=catalogdb;Port=5432;Database=catalogdb;Username=postgres;Password=password"
    ports:
      - "8080:8080"
    depends_on:
      - catalogdb